apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: relayserver-pv-claim
  namespace: ovr
  labels:
    app: ovr
  annotations:
    cdi.kubevirt.io/storage.import.endpoint: 0.0.0.0:8000/get-file/ovr-relay.tar.xz
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 35Gi
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: relayserver
  namespace: ovr
  generation: 1
  labels:
    kubevirt.io/os: linux
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: win2k12-iso
    spec:
      domain:
        cpu:
          cores: 2
        devices:
          disks:
          - disk:
              bus: virtio
            name: disk0
          - cdrom:
              bus: sata
              readonly: true
            name: cloudinitdisk
        machine:
          type: q35
        resources:
          requests:
            memory: 2Gi
      volumes:
      - name: disk0
        persistentVolumeClaim:
          claimName: relayserver-pv-claim
      - cloudInitNoCloud:
         userData: | 
            hostname: relayserver
            ssh_pwauth: true
            disable_root: false
            ssh_authorized_key:
            - ssh-rsa YOUR_SSH_PUB_KEY_HERE
        name: cloudinitdisk
