apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: plexus
  labels:
    app: plexus
spec:
  ports:
  - port: 7000
    targetPort: 3000
  selector:
    app: plexus
    tier: frontend
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pv-claim
  namespace: plexus
  labels:
    app: plexus
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: plexus
  labels:
    app: plexus
spec:
  selector:
    matchLabels:
      app: plexus
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: plexus
        tier: frontend
    spec:
      containers:
      - image: grafana/grafana:latest
        name: grafana
        resources:
          requests:
            cpu: 1
            memory: 55Mi
            ephemeral-storage: 200Mi
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: grafana
        volumeMounts:
        - name: grafana-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: grafana-persistent-storage
        persistentVolumeClaim:
          claimName: grafana-pv-claim
      nodeSelector:
        beta.kubernetes.io/os: linux
        resource: EdgeNode
