apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: plexus
  labels:
    app: plexus
spec:
  ports:
  - port: 7001
    targetPort: 8080
  selector:
    app: plexus
    tier: backend
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  namespace: plexus
  labels:
    app: plexus
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: plexus
  labels:
    app: plexus
spec:
  selector:
    matchLabels:
      app: plexus
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: plexus
        tier: backend
    spec:
      containers:
      - image: postgres:latest
        name: postgres
        resources:
          requests:
            cpu: 1
            memory: 55Mi
            ephemeral-storage: 200Mi
        imagePullPolicy: Always
        env:
        - name: POSTGRES_DB
          value: db0
        - name: POSTGRES_USER
          value: mendix
        - name: POSTGRES_PASSWORD
          value: mendix
        ports:
        - containerPort: 8080
          name: postgres
        volumeMounts:
        - name: postgres-persistent-storage
          mountPath: /var/lib/postgres
      volumes:
      - name: postgres-persistent-storage
        persistentVolumeClaim:
          claimName: postgres-pv-claim
      nodeSelector:
        beta.kubernetes.io/os: linux
        resource: EdgeNode
