openapi: 3.0.0
info:
  title: OpenApi 3.0 ReST interface for Accordion Orchestrator
  description: This is the Yaml file that goes with our server code
  version: 1.0.0
servers:
- url: /orchestrator
paths:
  /startapp:
    post:
      tags:
      - AppModel
      description: Start the execution of the deployment of an application with name AppName on the ACCORDION Federation
      operationId: appmodel_start_app
      parameters:
      - name: name
        in: query
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Succesfully start the deployment of the application with the submitted name
        default:
          description: Unexpected error
      x-openapi-router-controller: dynamic_orchestrator.controllers.app_model_controller