# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from dynamic_orchestrator.models.base_model_ import Model
from dynamic_orchestrator import util


class InlineResponse500(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, reason: str=None):  # noqa: E501
        """InlineResponse500 - a model defined in Swagger

        :param reason: The reason of this InlineResponse500.  # noqa: E501
        :type reason: str
        """
        self.swagger_types = {
            'reason': str
        }

        self.attribute_map = {
            'reason': 'reason'
        }
        self._reason = reason

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse500':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_500 of this InlineResponse500.  # noqa: E501
        :rtype: InlineResponse500
        """
        return util.deserialize_model(dikt, cls)

    @property
    def reason(self) -> str:
        """Gets the reason of this InlineResponse500.


        :return: The reason of this InlineResponse500.
        :rtype: str
        """
        return self._reason

    @reason.setter
    def reason(self, reason: str):
        """Sets the reason of this InlineResponse500.


        :param reason: The reason of this InlineResponse500.
        :type reason: str
        """

        self._reason = reason
